sudo: false
language: cpp
compiler:
  - clang
script: mkdir build && cd build && cmake .. -DSC_ENABLE_TESTING=ON && make -j3 && ctest -j2 --output-on-failure
branches:
  only:
    - master
notifications:
  irc: "chat.freenode.net#stepcode"
  email: scl-dev@groups.google.com
  on_success: change
  on_failure: always
os:
  - linux
  - osx
